apiVersion: apps/v1
kind: Deployment
metadata:
  name: gif-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gif
  template:
    metadata:
      labels:
        app: gif
    spec:
      containers:
        - name: gif
          image: gif-service:latest
          env:
            - name: SERVICE_PORT
              value: "8889"
            - name: REDIS_URL
              value: "redis:6379"
          resources:
            limits:
              memory: 50Mi
---
apiVersion: v1
kind: Service
metadata:
  name: gif-service
spec:
  selector:
    app: gif
  ports:
    - protocol: TCP
      port: 8889
      targetPort: 8889
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: redis-data
              mountPath: /data
      volumes:
        - name: redis-data
          emptyDir: {}
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: gif-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gif-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: 50
